kind: Deployment
apiVersion: apps/v1
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
        app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: vladimirab/gateway
        ports:
        - containerPort: 3000
        env:
        - name: USER_SERVICE_HOST
          value: "localhost"
        - name: KAFKA_HOST
          value: "192.168.1.240"
        - name: KAFKA_PORT
          value: "30718"
        - name: PORT
          value: "3000"
        - name: SECRET
          value: "secret"