apiVersion: apps/v1
kind: Deployment
metadata:
  name: kwetter
  labels:
    app: nginx
spec:
  replicas: 0
  selector:
    matchLabels:
      app: kwetter
  template:
    metadata:
      labels:
        app: kwetter
    spec:
      containers:
      - name: user-service
        image: vladimirab/user-service
        env:
        - name: SECRET
          value: "SECRET"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_NAME
          value: "user-service"
        - name: PORT
          value: "3501"
        - name: TCP
          value: "3500"
        ports:
        - containerPort: 3501
