name: User Service Pipeline
on:
  push:
    paths:
      - user-service/**
      - .github/workflows/user-service.yml
      - .github/workflows/composite/build/action.yml
      - .github/workflows/composite/deploy/action.yml

env:
  SERVICE_NAME: user-service
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_ZONE: europe-west4
  DEPLOYMENT_NAME: user-service-deployment
  GKE_CLUSTER: kwetter

jobs:
  testing:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ["12.x", "14.x", "16.x"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: |
        npm ci
        npm run build --if-present
        npm test
    - name: Lint with flake8
      run: |
        npm run lint
  
  build:
    needs: [testing]
    if: success()
    name: Build staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Build and Push
        uses: ./.github/workflows/composite/build
        with:
          service_name: ${{ env.SERVICE_NAME }}
          project_id: ${{ secrets.GOOGLE_CONTAINER_PROJECT_ID }}
          registry_token: ${{ secrets.GOOGLE_CONTAINER_REGISTRY_TOKEN }}

  deploy:
    needs: [build]
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Deploy to GKE
        uses: ./.github/workflows/composite/deploy
        with:
          service_account_key: ${{ secrets.GOOGLE_KUBERNETES_SERVICE_ACCOUNT }}
          project_id: ${{ secrets.GOOGLE_CONTAINER_PROJECT_ID }}
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GOOGLE_KUBERNETES_SERVICE_ACCOUNT }}
          deploy_name: ${{ env.DEPLOYMENT_NAME }}