name: Admin Service Pipeline
on:
  push:
    paths:
      - admin-service/**
      - .github/workflows/admin-service.yml
      - .github/workflows/composite/build/action.yml
      - .github/workflows/composite/deploy/action.yml

env:
  SERVICE_NAME: admin-service
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_ZONE: europe-west4
  DEPLOYMENT_NAME: admin-service-deployment
  GKE_CLUSTER: kwetter

jobs:
  testing:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ["12.x", "14.x", "16.x"]

    steps:
      - name: Copy repository
        uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm dependencies
        run: npm ci
      
      - name: Lint code
        run: npm run lint
  
  build:
    needs: [testing]
    if: success()
    name: Build staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Build and Push
        uses: ./.github/workflows/composite/build
        with:
          service_name: ${{ env.SERVICE_NAME }}
          project_id: ${{ secrets.GOOGLE_CONTAINER_PROJECT_ID }}
          registry_token: ${{ secrets.GOOGLE_CONTAINER_REGISTRY_TOKEN }}

  deploy:
    needs: [build]
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Deploy to GKE
        uses: ./.github/workflows/composite/deploy
        with:
          service_account_key: ${{ secrets.GOOGLE_KUBERNETES_SERVICE_ACCOUNT }}
          project_id: ${{ secrets.GOOGLE_CONTAINER_PROJECT_ID }}
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GOOGLE_KUBERNETES_SERVICE_ACCOUNT }}
          deploy_name: ${{ env.DEPLOYMENT_NAME }}