name: User Service Pipeline
on:
  push:
    paths:
      - user-service/**
      - .github/workflows/user-service.yml
      - .github/workflows/composite/build/action.yml
      - .github/workflows/composite/deploy/action.yml

env:
  SERVICE_NAME: user-service
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_ZONE: europe-west4
  DEPLOYMENT_NAME: user-service-deployment
  GKE_CLUSTER: kwetter

jobs:
  eslint:
    name: ES-Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source code
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install
        run: |
          npm i
        working-directory: user-service/

      - name: Check linting
        run: npm run lint:check
        working-directory: user-service/
  
  build:
    needs: [eslint]
    if: success()
    name: Build staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Build and Push
        uses: ./.github/workflows/composite/build
        with:
          service_name: ${{ env.SERVICE_NAME }}
          project_id: ${{ secrets.GOOGLE_CONTAINER_PROJECT_ID }}
          registry_token: ${{ secrets.GOOGLE_CONTAINER_REGISTRY_TOKEN }}